### ISSUE TITLE
Is this library use Turbo-Base64 through cgo?

### ISSUE THREAD

**Issue by chptx** [cristalhq/base64#2]
Or how this library  use Turbo-Base64?

**Comment by cristaloleg** [comment]
@IncSW

**Comment by IncSW** [comment]
@chptx
This is a pure golang, based on approaches from Turbo-Base64, without cgo, but uses unsafe.

**Comment by chptx** [comment]
@IncSW 
Is this library use SIMD as Turbo-Base64 do?

**Comment by IncSW** [comment]
Only scalar version.
